class Topo:
    def __init__(self, *args: object, **params: object) -> None: ...
    def build(self, *args: object, **params: object) -> None: ...
    def addHost(self, name: str, **opts: object) -> str: ...
    def addSwitch(self, name: str, **opts: object) -> str: ...
    def addLink(
        self,
        node1: str,
        node2: str,
        port1: int | None = None,
        port2: int | None = None,
        key: int | None = None,
        **opts: object,
    ) -> int: ...
